### ISSUE TITLE
chapter1: objdump

### ISSUE THREAD

**Issue by eyalpost** [teh-cmc/go-internals#23]
Question: Whats the difference between the output provided by the -S compile switch to the one that `go tool objdump` provides?

**Comment by teh-cmc** [comment]
They're pretty similar except for the fact that the output of `go tool objdump` is a bit closer to the "real" assembly language of the underlying hardware.  
E.g. platform-specific #defines are expanded (e.g. `TLS` becomes `FS:0`), references to `SP` are replaced by references to `IP`, etc...  
The output of `go tool objdump` is basically the output of `objdump -d` (which cannot parse Go object files) but with Go's assembly syntax and register naming conventions.

They also present different results in different ways, etc.  
There really isn't any efficient way of describing these differences with words though, your best bet is to write a simple program and compare the results of the followings for yourself:
- `go tool compile -S main.go`
- `go tool objdump main.o`
- `objdump -d main.bin`

You'll quickly get a clear idea of each tool's quirks.
