### ISSUE TITLE
meta: chinese translation?

### ISSUE THREAD

**Issue by ctriple** [teh-cmc/go-internals#24]
Hello, i am a native chinese speaker, and i am devoted to studying Golang also, and found that there is
little information about golang internals. your project seems like get this point. So let me work with you.
Let more chinese programmer understanding golang better.

**Comment by ctriple** [comment]
https://github.com/ctriple/go-internals/blob/master/README_zh_CN.md

I made a example for explain what i am planning to do.

**Comment by teh-cmc** [comment]
For sure, be my guest! :)

Just send me a PR e.g. when you're done with chapter I; and we'll figure out how to properly fit that work in here and credit you with the translation of course.

Thanks for the help!

**Comment by cch123** [comment]
@ctriple , I've already finished the translation for the first two chapters...

https://github.com/cch123/go-internals/tree/master/chapter1_assembly_primer/translations/cn

https://github.com/cch123/go-internals/tree/master/chapter2_interfaces/translations/cn

**Comment by ctriple** [comment]
ok, i want to make chinese version merged into the origin repo, would you please do this together.

**Comment by cch123** [comment]
@ctriple , ok, if the directory layout is accepted by the owner~
 I'll contribute my translation~

**Comment by ctriple** [comment]
@teh-cmc @cch123

**Comment by ctriple** [comment]
@teh-cmc you need to define the final directory layout, @cch123 and i for now just submit the sample example chapter to you. after you defined the layout, we will work on that layout for the other chapters. what do you think?

**Comment by cch123** [comment]
@ctriple @tmacychen , maybe we need to cooperate in some im tools.. you guys have qq or wechat?

**Comment by ghost** [comment]
yes, wechat group?  please contact me

**Comment by tmacychen** [comment]
wetchat : tmacy_chen

**Comment by cch123** [comment]
@teh-cmc , what about the translation procedure of this project https://github.com/0xAX/linux-insides, we create a fork repo of your project to translate it, upstream just needs to put a link on readme, and doesn't need to worry about the fixes of translations~

**Comment by cch123** [comment]
@teh-cmc , we'll work on Chinese translation in https://github.com/go-internals-cn/go-internals~ So just add this repo link~

**Comment by teh-cmc** [comment]
Done
