### ISSUE TITLE
meta: is this project still going on?

### ISSUE THREAD

**Issue by Delostik** [teh-cmc/go-internals#27]

**Comment by teh-cmc** [comment]
The last few months haven't been very kind when it comes to free time, unfortunately.

I already have written a ton of notes for chapters 3, 4 & 5 though, so... we'll see what the future holds.

**Comment by zerkms** [comment]
quality > pace

**Comment by FelixSeptem** [comment]
how is the progress now?still going on?

**Comment by kanishkatn** [comment]
Speed is God, time is the devil and change is the only constant
