### ISSUE TITLE
chapter 2: How you can get duplicated go.itab interface definitions

### ISSUE THREAD

**Issue by siebenmann** [teh-cmc/go-internals#7]
You asked why go.itabs are dupok. I believe the fundamental reason is that Go can be statically creating iface structures outside of either the package that defines the type or the package that defines the interface.

To make this concrete, here's a scenario where I believe that Go has to create duplicate ones. Suppose that we have four packages, A, B, C, D, and a main package. A defines a concrete type T, B defines an interface I (and perhaps some functions that take it), and both C and D import A and B and statically create B.I instances from A.T instances. Now we use both C and D in our main program.

Package A and B don't know about each other, so neither can define the iface<B.I, A.T> structure. Since C and D may be used by themselves, each must define this separately; they both need it and they have no guaranteed source of it outside themselves. Then when we use both of them together in our main program, we have duplicate definitions of iface<B.I, A.T>, one from each package, so Go must make such duplicates harmless.

**Comment by teh-cmc** [comment]
I've added a link to this discussion in the relevant part of chapter 2; and will be closing this now.
*Don't hesitate to add more comments even if it's closed!*

Hopefully I'll take the time to update chapter 2 with all these learnings some day.
