### ISSUE TITLE
meta: talk about compiler internals?

### ISSUE THREAD

**Issue by feilengcui008** [teh-cmc/go-internals#8]
have read the first two chapters, it's really amazing! 

any plans for writing compiling part as well as runtime?

**Comment by teh-cmc** [comment]
For now, the main focus is on everything that impacts the behaviour of the running program, which most of the time encompass the runtime itself as well as some interesting parts of the standard library.

In some cases though, such as the implementation of interfaces or the garbage collector, the behavior of the runtime is tightly coupled to data that's generated by the compiler (e.g. vtables).  
In these cases, we try and get a deep understanding of where this generated data is and what it's made of; but we don't actually look at the code that generates it, as it's irrelevant with regards to the behaviour of the final program.

Maybe once we're done with everything that relates to run time behavior, we'll then have try and have a look at the actual compiler internals, who knows... but we are far, far from being there though. :)
